-- Script de Criação (DDL)
CREATE DATABASE clinicavet_db;
USE clinicavet_db;

-- Tabela CLIENTE
CREATE TABLE CLIENTE (
  ID_Cliente INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL,
  Telefone VARCHAR(15) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Cliente)
);

-- Tabela PET
CREATE TABLE PET (
  FK_ID_Cliente INT NOT NULL,
  ID_PET INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL,
  Especie VARCHAR(50) NULL,
  Idade INT NOT NULL,
  PRIMARY KEY (ID_Produto),
  FOREIGN KEY (ID_Cliente) REFERENCES Cliente(ID_Cliente)
);

-- Tabela VET
CREATE TABLE VET (
  ID_VET INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL,
  CRMV VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID_VET)
);

-- Tabela CONSULTA
CREATE TABLE CONSULTA (
  FK_ID_Pet INT NOT NULL,
  FK_ID_VET INT NOT NULL,
  ID_CONSULTA INT NOT NULL AUTO_INCREMENT,
  DATA_CONSULTA DATE NOT NULL,
  Tipo_servico VARCHAR(255),
  PRIMARY KEY (ID_CONSULTA),
  FOREIGN KEY (ID_VET) REFERENCES VET(ID_VET)
  FOREIGN KEY (ID_PET) REFERENCES PET(ID_PET)
);

-- Tabela MED
CREATE TABLE MED (
  FK_ID_CONSULTA INT NOT NULL,
  ID_MED INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL,
  QUANTIDADE INT NOT NULL,
  VALIDADE DATE NOT NULL,
  PRIMARY KEY (ID_MED),
  FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
);

-- Tabela MED_CONSULTA
CREATE TABLE MED_CONSULTA (
  FK_ID_CONSULTA INT NOT NULL,
  FK_ID_MED INT NOT NULL,
  ID_MED_CONSULTA INT NOT NULL AUTO_INCREMENT,
  Dose_aplicada VARCHAR(100) NOT NULL,
  FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA)
  FOREIGN KEY (ID_MED) REFERENCES MED(ID_MED)
);
